### ISSUE TITLE
Blocks are no longer assigned to regions after updating to version 3.4.0

### ISSUE THREAD

**Issue by kanarb** [knice/ucsc-drupal#44]
When updating from 3.1.0 to 3.4.0 most of my blocks lose their regions.
![3 1 0](https://cloud.githubusercontent.com/assets/5742093/15156468/0b01f252-169c-11e6-912e-f5fbddb0b214.png)
![3 4 0](https://cloud.githubusercontent.com/assets/5742093/15156471/0e7bcdf4-169c-11e6-8f0e-42368da8952b.png)

**Comment by kanarb** [comment]
I think this is actually an issue with an earlier version. I seem to remember seeing this when updating the theme from 3.1 to 3.2 or 3.3 on my dev.

**Comment by knice** [comment]
You probably had this happen because [3.2 changed the folder name of the theme](https://github.com/knice/ucsc-drupal/releases/tag/3.2.0). SOE still uses previous versions of the theme and couldn't have two folders called `ucsc` in the themes folder. 

I'm not sure if there is a way around this since the name change affected the .info file as well.

**Comment by kanarb** [comment]
Got it. I'll reassign the blocks. By the way, I'm doing some more testing
and I'm not seeing the padding around images. Issue:
https://github.com/knice/ucsc-drupal/issues/43
